import{S as u,i as c}from"./assets/vendor-0fc460d7.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&r(s)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();function d(i){return fetch(`https://pixabay.com/api/?key=45098523-0f66f1bf08e0be6a1e71621a5&q=${i}&image_type=photo&orientation=horizontal&safesearch=true`).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()})}const f="../img/icon.svg";function p(i){const n=document.querySelector(".gallery");n.innerHTML="",i.forEach(t=>{const r=document.createElement("a");r.href=t.largeImageURL,r.classList.add("image-card"),r.innerHTML=`
      <img src="${t.webformatURL}" alt="${t.tags}" title="${t.tags}" />
      <div class="info">
        <p><strong>Likes:</strong> ${t.likes}</p>
        <p><strong>Views:</strong> ${t.views}</p>
        <p><strong>Comments:</strong> ${t.comments}</p>
        <p><strong>Downloads:</strong> ${t.downloads}</p>
      </div>
    `,n.appendChild(r)}),window.lightbox?window.lightbox.refresh():window.lightbox=new u(".gallery a",{})}function g(i){const n=document.getElementById("loader");n.style.display="none",c.error({title:"",message:`Failed to fetch images: ${i.message}`,iconUrl:`${f}#icon-Group-1`,position:"topRight",backgroundColor:"red"})}const l=document.querySelector(".form-inline");document.querySelector(".image-container");const a=document.querySelector(".loader");l.addEventListener("submit",m);function m(i){i.preventDefault();const t=i.currentTarget.elements.query.value.trim().toLowerCase();if(t===""){c.warning({title:"",message:"Search query cannot be empty.",position:"topRight",backgroundColor:"red",icon:"",iconUrl:`${pathSprite}#icon-Group-1`});return}a.style.display="block",d(t).then(r=>{r.hits.length>0?p(r.hits):c.warning({title:"",backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",iconUrl:`${pathSprite}#icon-Group-1`})}).catch(g).finally(()=>{a.style.display="none",l.reset()})}
//# sourceMappingURL=commonHelpers.js.map
